Finished deb file packaging, and init scripts.  Should be good to deploy.  Next to see if I can get a proper ubuntu PPA setup.

diff --git a/appdev/releases/deb/DEBIAN/prerm b/appdev/releases/deb/DEBIAN/prerm
--- a/appdev/releases/deb/DEBIAN/prerm
+++ b/appdev/releases/deb/DEBIAN/prerm
@@ -1,1 +1,46 @@
-service freehold uninstall
+#!/bin/sh
+# prerm script for freehold
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+echo "arg: $1"
+
+case "$1" in
+    remove|upgrade|deconfigure)
+    ;;
+
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+# Automatically added by dh_installinit
+if [ -x "/etc/init.d/freehold" ] || [ -e "/etc/init/freehold.conf" ]; then
+	invoke-rc.d freehold stop || exit $?
+fi
+# End automatically added section
+
+
+exit 0
+
+
